// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quinela.Infrastructure.Persistence;

#nullable disable

namespace Quinela.Infrastructure.Migrations
{
    [DbContext(typeof(QuinelaContext))]
    [Migration("20260609015320_AddTipoPartido")]
    partial class AddTipoPartido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Quinela.Domain.Entities.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<bool>("Anfitrion")
                        .HasColumnType("boolean")
                        .HasColumnName("anfitrion");

                    b.Property<string>("Confederacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("confederacion");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("created_by");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("equipos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Anfitrion = true,
                            Confederacion = "CONCACAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "México"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Sudáfrica"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "AFC",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Corea del Sur"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "República Checa"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            Anfitrion = true,
                            Confederacion = "CONCACAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Canadá"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Bosnia y Herzegovina"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "AFC",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Qatar"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Suiza"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CONMEBOL",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Brasil"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Marruecos"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CONCACAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Haití"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Escocia"
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            Anfitrion = true,
                            Confederacion = "CONCACAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Estados Unidos"
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CONMEBOL",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Paraguay"
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "AFC",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Australia"
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Turquía"
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Alemania"
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CONCACAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Curazao"
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Costa de Marfil"
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CONMEBOL",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Ecuador"
                        },
                        new
                        {
                            Id = 21,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Países Bajos"
                        },
                        new
                        {
                            Id = 22,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "AFC",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Japón"
                        },
                        new
                        {
                            Id = 23,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Suecia"
                        },
                        new
                        {
                            Id = 24,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Túnez"
                        },
                        new
                        {
                            Id = 25,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Bélgica"
                        },
                        new
                        {
                            Id = 26,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Egipto"
                        },
                        new
                        {
                            Id = 27,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "AFC",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Irán"
                        },
                        new
                        {
                            Id = 28,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "OFC",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Nueva Zelanda"
                        },
                        new
                        {
                            Id = 29,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "España"
                        },
                        new
                        {
                            Id = 30,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Cabo Verde"
                        },
                        new
                        {
                            Id = 31,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "AFC",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Arabia Saudita"
                        },
                        new
                        {
                            Id = 32,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CONMEBOL",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Uruguay"
                        },
                        new
                        {
                            Id = 33,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Francia"
                        },
                        new
                        {
                            Id = 34,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Senegal"
                        },
                        new
                        {
                            Id = 35,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "AFC",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Irak"
                        },
                        new
                        {
                            Id = 36,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Noruega"
                        },
                        new
                        {
                            Id = 37,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CONMEBOL",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Argentina"
                        },
                        new
                        {
                            Id = 38,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Argelia"
                        },
                        new
                        {
                            Id = 39,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Austria"
                        },
                        new
                        {
                            Id = 40,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "AFC",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Jordania"
                        },
                        new
                        {
                            Id = 41,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Portugal"
                        },
                        new
                        {
                            Id = 42,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "RD Congo"
                        },
                        new
                        {
                            Id = 43,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "AFC",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Uzbekistán"
                        },
                        new
                        {
                            Id = 44,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CONMEBOL",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Colombia"
                        },
                        new
                        {
                            Id = 45,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Inglaterra"
                        },
                        new
                        {
                            Id = 46,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "UEFA",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Croacia"
                        },
                        new
                        {
                            Id = 47,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Ghana"
                        },
                        new
                        {
                            Id = 48,
                            Active = true,
                            Anfitrion = false,
                            Confederacion = "CONCACAF",
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "Panamá"
                        });
                });

            modelBuilder.Entity("Quinela.Domain.Entities.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("created_by");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("nombre");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("grupos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "A"
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "B"
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "C"
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "D"
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "E"
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "F"
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "G"
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "H"
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "I"
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "J"
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "K"
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Nombre = "L"
                        });
                });

            modelBuilder.Entity("Quinela.Domain.Entities.GrupoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("created_by");

                    b.Property<int>("Diff")
                        .HasColumnType("integer")
                        .HasColumnName("diff");

                    b.Property<int>("EquipoId")
                        .HasColumnType("integer")
                        .HasColumnName("equipo_id");

                    b.Property<int>("GC")
                        .HasColumnType("integer")
                        .HasColumnName("gc");

                    b.Property<int>("GF")
                        .HasColumnType("integer")
                        .HasColumnName("gf");

                    b.Property<int>("GrupoId")
                        .HasColumnType("integer")
                        .HasColumnName("grupo_id");

                    b.Property<int>("Posicion")
                        .HasColumnType("integer")
                        .HasColumnName("posicion");

                    b.Property<int>("Pts")
                        .HasColumnType("integer")
                        .HasColumnName("pts");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("GrupoId", "EquipoId")
                        .IsUnique();

                    b.ToTable("grupos_equipos", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 1,
                            GC = 0,
                            GF = 0,
                            GrupoId = 1,
                            Posicion = 1,
                            Pts = 0
                        },
                        new
                        {
                            Id = 2,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 2,
                            GC = 0,
                            GF = 0,
                            GrupoId = 1,
                            Posicion = 2,
                            Pts = 0
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 3,
                            GC = 0,
                            GF = 0,
                            GrupoId = 1,
                            Posicion = 3,
                            Pts = 0
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 4,
                            GC = 0,
                            GF = 0,
                            GrupoId = 1,
                            Posicion = 4,
                            Pts = 0
                        },
                        new
                        {
                            Id = 5,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 5,
                            GC = 0,
                            GF = 0,
                            GrupoId = 2,
                            Posicion = 1,
                            Pts = 0
                        },
                        new
                        {
                            Id = 6,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 6,
                            GC = 0,
                            GF = 0,
                            GrupoId = 2,
                            Posicion = 2,
                            Pts = 0
                        },
                        new
                        {
                            Id = 7,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 7,
                            GC = 0,
                            GF = 0,
                            GrupoId = 2,
                            Posicion = 3,
                            Pts = 0
                        },
                        new
                        {
                            Id = 8,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 8,
                            GC = 0,
                            GF = 0,
                            GrupoId = 2,
                            Posicion = 4,
                            Pts = 0
                        },
                        new
                        {
                            Id = 9,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 9,
                            GC = 0,
                            GF = 0,
                            GrupoId = 3,
                            Posicion = 1,
                            Pts = 0
                        },
                        new
                        {
                            Id = 10,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 10,
                            GC = 0,
                            GF = 0,
                            GrupoId = 3,
                            Posicion = 2,
                            Pts = 0
                        },
                        new
                        {
                            Id = 11,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 11,
                            GC = 0,
                            GF = 0,
                            GrupoId = 3,
                            Posicion = 3,
                            Pts = 0
                        },
                        new
                        {
                            Id = 12,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 12,
                            GC = 0,
                            GF = 0,
                            GrupoId = 3,
                            Posicion = 4,
                            Pts = 0
                        },
                        new
                        {
                            Id = 13,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 13,
                            GC = 0,
                            GF = 0,
                            GrupoId = 4,
                            Posicion = 1,
                            Pts = 0
                        },
                        new
                        {
                            Id = 14,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 14,
                            GC = 0,
                            GF = 0,
                            GrupoId = 4,
                            Posicion = 2,
                            Pts = 0
                        },
                        new
                        {
                            Id = 15,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 15,
                            GC = 0,
                            GF = 0,
                            GrupoId = 4,
                            Posicion = 3,
                            Pts = 0
                        },
                        new
                        {
                            Id = 16,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 16,
                            GC = 0,
                            GF = 0,
                            GrupoId = 4,
                            Posicion = 4,
                            Pts = 0
                        },
                        new
                        {
                            Id = 17,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 17,
                            GC = 0,
                            GF = 0,
                            GrupoId = 5,
                            Posicion = 1,
                            Pts = 0
                        },
                        new
                        {
                            Id = 18,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 18,
                            GC = 0,
                            GF = 0,
                            GrupoId = 5,
                            Posicion = 2,
                            Pts = 0
                        },
                        new
                        {
                            Id = 19,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 19,
                            GC = 0,
                            GF = 0,
                            GrupoId = 5,
                            Posicion = 3,
                            Pts = 0
                        },
                        new
                        {
                            Id = 20,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 20,
                            GC = 0,
                            GF = 0,
                            GrupoId = 5,
                            Posicion = 4,
                            Pts = 0
                        },
                        new
                        {
                            Id = 21,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 21,
                            GC = 0,
                            GF = 0,
                            GrupoId = 6,
                            Posicion = 1,
                            Pts = 0
                        },
                        new
                        {
                            Id = 22,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 22,
                            GC = 0,
                            GF = 0,
                            GrupoId = 6,
                            Posicion = 2,
                            Pts = 0
                        },
                        new
                        {
                            Id = 23,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 23,
                            GC = 0,
                            GF = 0,
                            GrupoId = 6,
                            Posicion = 3,
                            Pts = 0
                        },
                        new
                        {
                            Id = 24,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 24,
                            GC = 0,
                            GF = 0,
                            GrupoId = 6,
                            Posicion = 4,
                            Pts = 0
                        },
                        new
                        {
                            Id = 25,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 25,
                            GC = 0,
                            GF = 0,
                            GrupoId = 7,
                            Posicion = 1,
                            Pts = 0
                        },
                        new
                        {
                            Id = 26,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 26,
                            GC = 0,
                            GF = 0,
                            GrupoId = 7,
                            Posicion = 2,
                            Pts = 0
                        },
                        new
                        {
                            Id = 27,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 27,
                            GC = 0,
                            GF = 0,
                            GrupoId = 7,
                            Posicion = 3,
                            Pts = 0
                        },
                        new
                        {
                            Id = 28,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 28,
                            GC = 0,
                            GF = 0,
                            GrupoId = 7,
                            Posicion = 4,
                            Pts = 0
                        },
                        new
                        {
                            Id = 29,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 29,
                            GC = 0,
                            GF = 0,
                            GrupoId = 8,
                            Posicion = 1,
                            Pts = 0
                        },
                        new
                        {
                            Id = 30,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 30,
                            GC = 0,
                            GF = 0,
                            GrupoId = 8,
                            Posicion = 2,
                            Pts = 0
                        },
                        new
                        {
                            Id = 31,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 31,
                            GC = 0,
                            GF = 0,
                            GrupoId = 8,
                            Posicion = 3,
                            Pts = 0
                        },
                        new
                        {
                            Id = 32,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 32,
                            GC = 0,
                            GF = 0,
                            GrupoId = 8,
                            Posicion = 4,
                            Pts = 0
                        },
                        new
                        {
                            Id = 33,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 33,
                            GC = 0,
                            GF = 0,
                            GrupoId = 9,
                            Posicion = 1,
                            Pts = 0
                        },
                        new
                        {
                            Id = 34,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 34,
                            GC = 0,
                            GF = 0,
                            GrupoId = 9,
                            Posicion = 2,
                            Pts = 0
                        },
                        new
                        {
                            Id = 35,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 35,
                            GC = 0,
                            GF = 0,
                            GrupoId = 9,
                            Posicion = 3,
                            Pts = 0
                        },
                        new
                        {
                            Id = 36,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 36,
                            GC = 0,
                            GF = 0,
                            GrupoId = 9,
                            Posicion = 4,
                            Pts = 0
                        },
                        new
                        {
                            Id = 37,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 37,
                            GC = 0,
                            GF = 0,
                            GrupoId = 10,
                            Posicion = 1,
                            Pts = 0
                        },
                        new
                        {
                            Id = 38,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 38,
                            GC = 0,
                            GF = 0,
                            GrupoId = 10,
                            Posicion = 2,
                            Pts = 0
                        },
                        new
                        {
                            Id = 39,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 39,
                            GC = 0,
                            GF = 0,
                            GrupoId = 10,
                            Posicion = 3,
                            Pts = 0
                        },
                        new
                        {
                            Id = 40,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 40,
                            GC = 0,
                            GF = 0,
                            GrupoId = 10,
                            Posicion = 4,
                            Pts = 0
                        },
                        new
                        {
                            Id = 41,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 41,
                            GC = 0,
                            GF = 0,
                            GrupoId = 11,
                            Posicion = 1,
                            Pts = 0
                        },
                        new
                        {
                            Id = 42,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 42,
                            GC = 0,
                            GF = 0,
                            GrupoId = 11,
                            Posicion = 2,
                            Pts = 0
                        },
                        new
                        {
                            Id = 43,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 43,
                            GC = 0,
                            GF = 0,
                            GrupoId = 11,
                            Posicion = 3,
                            Pts = 0
                        },
                        new
                        {
                            Id = 44,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 44,
                            GC = 0,
                            GF = 0,
                            GrupoId = 11,
                            Posicion = 4,
                            Pts = 0
                        },
                        new
                        {
                            Id = 45,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 45,
                            GC = 0,
                            GF = 0,
                            GrupoId = 12,
                            Posicion = 1,
                            Pts = 0
                        },
                        new
                        {
                            Id = 46,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 46,
                            GC = 0,
                            GF = 0,
                            GrupoId = 12,
                            Posicion = 2,
                            Pts = 0
                        },
                        new
                        {
                            Id = 47,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 47,
                            GC = 0,
                            GF = 0,
                            GrupoId = 12,
                            Posicion = 3,
                            Pts = 0
                        },
                        new
                        {
                            Id = 48,
                            Active = true,
                            CreatedAt = new DateTime(2026, 6, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedBy = "seed",
                            Diff = 0,
                            EquipoId = 48,
                            GC = 0,
                            GF = 0,
                            GrupoId = 12,
                            Posicion = 4,
                            Pts = 0
                        });
                });

            modelBuilder.Entity("Quinela.Domain.Entities.TipoPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("created_by");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("descripcion");

                    b.Property<int>("PtsPartidoEmpate")
                        .HasColumnType("integer")
                        .HasColumnName("pts_partido_empate");

                    b.Property<int>("PtsPartidoVictoria")
                        .HasColumnType("integer")
                        .HasColumnName("pts_partido_victoria");

                    b.Property<int>("PtsQuinelaResultadoAcertado")
                        .HasColumnType("integer")
                        .HasColumnName("pts_quinela_resultado_acertado");

                    b.Property<int>("PtsQuinelaResultadoExacto")
                        .HasColumnType("integer")
                        .HasColumnName("pts_quinela_resultado_exacto");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id");

                    b.HasIndex("Descripcion")
                        .IsUnique();

                    b.ToTable("tipos_partido", (string)null);
                });

            modelBuilder.Entity("Quinela.Domain.Entities.GrupoEquipo", b =>
                {
                    b.HasOne("Quinela.Domain.Entities.Equipo", "Equipo")
                        .WithMany("GrupoEquipos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Quinela.Domain.Entities.Grupo", "Grupo")
                        .WithMany("GrupoEquipos")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("Quinela.Domain.Entities.Equipo", b =>
                {
                    b.Navigation("GrupoEquipos");
                });

            modelBuilder.Entity("Quinela.Domain.Entities.Grupo", b =>
                {
                    b.Navigation("GrupoEquipos");
                });
#pragma warning restore 612, 618
        }
    }
}
